export const GET_USERS_RESULTS = "GET_USERS_RESULTS";
export const GET_USERS_RESULTS_RESPONSE = "GET_USERS_RESULTS_RESPONSE";
export const GET_USERS_SEARCH_RESULTS = "GET_USERS_SEARCH_RESULTS";
export const GET_USERS_SEARCH_RESULTS_RESPONSE = "GET_USERS_SEARCH_RESULTS_RESPONSE";
